version: '2'
services:
  pedestrian_detection:
    command: '/ie-serving-py/start_server.sh ie_serving model --model_path /opt/ml/pedestrian_detection_server --model_name pedestrian_detection_server --port 9001 --rest_port 8001'
    image: 'ccr.ccs.tencentyun.com/aiot-test/pedestrian_detection:latest'
    container_name: pedestrian_detection
