version: '2'
services:
  pose_estimation:
    command: /bin/bash -c "source /opt/intel/openvino/bin/setupvars.sh && /ie-serving-py/start_server.sh ie_serving model --model_path /opt/ml/pose_estimation_hddl --model_name pose_estimation_hddl --port 9001 --rest_port 8001"
    image: 'ccr.ccs.tencentyun.com/aiot-test/pose_estimation_hddl:latest'
    container_name: pose_estimation
    volumes:
      - /var/tmp:/var/tmp
      - /dev:/dev
    devices:
      - /dev/ion:/dev/ion
    labels:
      com_mwp_conf_nginx: '[]'
      com_mwp_conf_services: '{"function_ids":[],"google_function":false,"pub_sub":false,"mDNS":false,"secretList":[],"secret":false,"configList":[],"config":false}'
      com_mwp_conf_storage: '{"usb":false}'
    environment:
      - DEVICE=HDDL
      - CPU_EXTENSION=/libcpu_extension_sse4.so
